### ISSUE TITLE
Consider moving Cake.Git dependency with a separate NuGet library

### ISSUE THREAD

**Issue by pleonex** [cake-contrib/Cake.Issues.Recipe#383]
As far as I understand, this recipe can either use Cake.Git or the Git CLI to get some information. Personally I prefer Git CLI as I always have issues with libgit2sharp native libraries in Linux distros (having incompatible glibc versions).
If I choose to use the Git CLI, I would still have the dependency with Cake.Git which I shouldn't need. This causes some issues:

- Libgit2sharp along all of its native libraries for all OSes are downloaded and copied to the output folder
- Due to [Cake.Git issue 137](https://github.com/cake-contrib/Cake_Git/issues/137), adding a reference to Cake.Issues.Recipe will cause a warning in my project. Furthermore, I won't be able to use dotnet-script to write my build scripts.

The suggestion is to move the code that uses Cake.Git into a separate NuGet, just like Cake.Issues.DocFx, so if you choose the CLI version you don't have that dependency.

**Comment by pascalberger** [comment]
Moving code into a separate NuGet package won't make a difference, since Libgit2sharp is already wrapped in a separate NuGet package (Cake.Git). Cake.Issues.DocFx is also not an example which you can compare, since DocFx log file parsing is not supported out of the box in the recipe. Other issue provider (e.g. Cake.Issues.MsBuild) are also downloaded everytime.
What would be required is dynamic loading of the addins which are required based on configuration (#17).
